server:
  port: 8001

spring:
  application:
    name: jih-manage
  datasource:
    name: test
    url: jdbc:mysql://111.231.231.56/jih
    username: admin
    password: 15038705068aa
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
  type-aliases-package: com.xiaolc.model
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: jih-manage
    prefer-ip-address: true
  server:
      enable-self-preservation: false
#enable-self-preservation: false
info:
  app.name: jih-manage
  company.name: www.manage.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
springfox.documentation.swagger.v2.path: /api-docs
